package controller;

import java.io.IOException;

import classes.User;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

/**
* @author Rohit Deshmukh
* The signUpPage_Controller class is a controller for the sign-up page of the application.
* It handles user input and creates new User objects upon successful user creation.
*/

public class signUpPage_Controller {

    @FXML
    private Button signUp_Cancel;

    @FXML
    private Button signUp_Create;

    @FXML
    private TextField signUp_password;

    @FXML
    private TextField signUp_username;

    /**
     * This method handles the "Cancel" button being pressed, which brings the user back to the login page.
     * @param event The action event generated by the "Cancel" button press.
     * @throws IOException If there is an issue loading the login page FXML file.
     */
    @FXML
    void signUp_cancel_Handler(ActionEvent event) throws IOException {
        Stage stage = (Stage) signUp_Cancel.getScene().getWindow();
        Parent root = FXMLLoader.load(getClass().getResource("/scene/loginPage.fxml"));
        Scene scene = new Scene(root);
        stage.setScene(scene);
    }

    /**
     * This method handles the "Create" button being pressed, which attempts to create a new user account.
     * If the input is valid, a new User object is created and the user is brought back to the login page.
     * If the input is invalid, an error alert is displayed.
     * @param event The action event generated by the "Create" button press.
     */
    @FXML
    void signUp_create_Handler(ActionEvent event) {

        Alert invalidAlert = new Alert(AlertType.ERROR);
        invalidAlert.setHeaderText("Input not valid");
        invalidAlert.setContentText("Input is not valid");
        String username = signUp_username.getText();
        String password = signUp_password.getText();

        try {

            new User(username, password);

            Stage stage = (Stage) signUp_Create.getScene().getWindow();
            Parent root = FXMLLoader.load(getClass().getResource("/scene/loginPage.fxml"));
            Scene scene = new Scene(root);
            stage.setScene(scene);

        } catch (Exception e) {
            invalidAlert.setContentText(e.toString());
            invalidAlert.showAndWait();
        }
       
    }    

}
